### ISSUE TITLE
[WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]

### ISSUE THREAD

**Issue by Letsplaybar** [WooMinecraft/WooMinecraft#109]
Hallo,
ich habe folgendes Problem:
wenn ich im Shop etwas in WooMinecraft kaufe und ich dann auf dem Server /woo check eingebe kommt die oben genannte Fehlermeldung. Der Kunde bekommt zwar sein gekauftes Packet aber dies wird nicht removed so das beim nächsten /woo check immer noch der Fehler kommt und er sein gekauftes Packet wieder bekommt. Sobald ich dies manuell removed habe kommt die Standart Massage. wie kann ich das Problem beheben???
Version: 1.0.6 Minecraft
Version: 1.0.6 Wordpress
Hier die Config Datei:
# Set this to the desired language file you wish to load.
lang: de
update_interval: 1500
url: http://letsplaybar.de
key: [der gleiche wie im Shop]
debug: false

MfG
Letsplaybar

translate Version:
sorry for terrible english.
I have the problem if evrywone by a product from my WooMinecraft of my Wordpress side,  then he is in the Minecraftserver and I make /woo check, became he the product but it wouldn't delet so that he became everytime when i make /woo check or the scheduler the methode run, the product again.
config see top.

friendly
Letsplaybar

**Comment by JayWood** [comment]
Es tut mir leid , aber das ist Text übersetzt - Können Sie vorausgesetzt der Server Schlüssel , und der Spieler , der zu dem Zeitpunkt in der Befehl protokolliert wurde sollte für sein lief ? Ich werde den Beitrag bearbeiten und löschen Sie es , wenn ich es haben.

**Comment by Letsplaybar** [comment]
Wäre nett wenn sie es einfach nochmal auf englisch schreiben können da dies kaum zu verstehen ist.

Please write the anther in english. this German is incomprehensible. i can read english, but terible write. :D

**Comment by JayWood** [comment]
Awesome, thanks for that. Can you provide your server key, as well as a player name who has pending commands, if you have no players who have pending commands use my IGN as a user `Phyrax`

**Comment by Letsplaybar** [comment]
He is a video with what i make to this mistake to produce: https://youtu.be/EnOCf7Eoh64
and he is my Server Key c5d1bb7e5d0449bd9709513bd89b2fe4

**Comment by JayWood** [comment]
@Letsplaybar OH I see now, I can't thank you enough for doing a video for this... it helps tremendously. The issue isn't sending the commands from WordPress to you, that seems to be great. But it's after that happens that's causing the error. Which in-turn is causing the data to not be sent back to your server, or your server isn't processing the data.

Would you mind ( on your server ) using my IGN `Phyrax` and purchase something small, just so I can test a few more things remotely?

**Comment by Letsplaybar** [comment]
Why do you see have i about your IGN Phyrax a little pack of coins buyed. 
http://prntscr.com/cafibb here a picture from this.
my Server ip is letsplaybar.de

**Comment by JayWood** [comment]
![2c6c8a87a4b33c463f206fc0958258cb](https://cloud.githubusercontent.com/assets/2303074/17986886/f7ac9fce-6aea-11e6-9016-e8061e8d5f6f.png)

Great, yep I have it. I'm quite busy right now but please leave that order there and I'll do some testing. Also, for future reference, you do not need to store the commands with a slash `/` the code in the minecraft plugin does that for you.

**Comment by Letsplaybar** [comment]
This have do a admin for me, i have it Change. And by this packet have I forgot this.

**Comment by JayWood** [comment]
@Letsplaybar I've tried my hardest to duplicate this by normal means ( sending updates to the plugin via JSON ) basically mimicking how the minecraft server would do it with your server. For the life of me I cannot replicate the issue.

Therefore, I just released a maintenance release to print these stack traces instead of this vague message.

You can get it here https://github.com/WooMinecraft/WooMinecraft/releases/tag/1.0.7
Or on Spigot - https://www.spigotmc.org/resources/woominecraft.25517/

Would you kindly install this update, and run the same command again? Once that's done you should get a full stack trace in your log, if you can post your log or the stack trace ( huge error ) that will help me track it down.

**Comment by Letsplaybar** [comment]
Sorry that i jet write first. here the erorror log:
`[16:39:30] [Server thread/INFO]: Letsplaybar issued server command: /woo check
[16:39:30] [Server thread/WARN]: [WooMinecraft] null
[16:39:30] [Server thread/WARN]: java.lang.NullPointerException
[16:39:30] [Server thread/WARN]: 	at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:157)
[16:39:30] [Server thread/WARN]: 	at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:59)
[16:39:30] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:39:30] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:39:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:39:30] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[16:39:30] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[16:39:30] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:39:30] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:39:30] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:39:30] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:39:30] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:39:30] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:39:30] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:39:30] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:39:30] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:39:30] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:39:30] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
`
i hope that can help you.

**Comment by Jogib** [comment]
@Letsplaybar 
Read from [here](https://github.com/WooMinecraft/WooMinecraft/issues/106#issuecomment-243324422) 
@JayWood and I already fixed it.

Just waiting on his next release.

**Comment by eric2788** [comment]
i met a same problem too
version: https://gyazo.com/3a5e8f9651b5364711369161f9dd4a70
using spigot 1.10.2
error when issued product command: https://gyazo.com/a4d15033b013665ebb274d8f409e7dbe
error when used /woo check: https://gyazo.com/75b16a109be5aa45cbccfd7503b9234d

**Comment by eric2788** [comment]
and also i will timed loop the product command i have bought a long time ago......

**Comment by JayWood** [comment]
@eric2788 make sure you're on the latest version ( downloadable [here](https://github.com/WooMinecraft/WooMinecraft/releases) )

You can also download the latest pre-release which adds a debug flag ( and is more helpful in your logs ).

Also you will want to check your config for the plugin in bukkit, as the previous two issue here were solved by making sure it wasn't blank. It should look like this:

```lang: "en"
update_interval: 1500
url: "http://playground.dev"
key: ""
debug: false```

Replace the URL and Key with your stuff.

**Comment by JayWood** [comment]
I'll have an update to this code by tomorrow evening, thanks for your patients guys.

**Comment by eric2788** [comment]
i have used 1.0.8 pre release
but
when i used /woo register
it take config.yml only leave a key: "xxxxxxxxxxxxxxxx"
and all option was gone
also

> and also it will timed loop the product command i have bought a long time ago......

this bug still happen on this latest version

**Comment by JayWood** [comment]
@Letsplaybar I've not released the fix for that yet, will do sometime today. The reason your server will 'loop the product command' is it's erroring out and not sending data back to the server.

**Comment by JayWood** [comment]
@eric2788 Read above, put all the config items IN your config file.

**Comment by eric2788** [comment]
@JayWood  here's all the bugs i have found
https://github.com/WooMinecraft/WooMinecraft/issues/111

**Comment by JayWood** [comment]
@eric2788 no need to cross post :smile: there's not a ton of tickets to sift through, so I read them all :+1: 

@Jogib @Letsplaybar update is up, as always download and let me know ( wordpress AND java )

**Comment by Letsplaybar** [comment]
@JayWood the error comes again.
`
[00:14:41] [Server thread/INFO]: Letsplaybar issued server command: /woo check
[00:14:41] [Server thread/WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]
[00:14:41] [Server thread/WARN]: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
[00:14:41] [Server thread/WARN]: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[00:14:41] [Server thread/WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:195)
[00:14:41] [Server thread/WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:319)
[00:14:41] [Server thread/WARN]: 	at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:135)
[00:14:41] [Server thread/WARN]: 	at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:59)
[00:14:41] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:14:41] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:14:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[00:14:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[00:14:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[00:14:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:14:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:14:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[00:14:41] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:14:41] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:14:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[00:14:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[00:14:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[00:14:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[00:14:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[00:14:41] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
`
this is the log have updated Wordpress to 1.0.8 and Minecraft to 1.0.9.
and the produkt have i new buyed and the old removed.

**Comment by Jogib** [comment]
This error still pops up.

**Comment by eric2788** [comment]
@Jogib  omg..........expecting next version ....

**Comment by eric2788** [comment]
@Letsplaybar  have this plugin looped the product command ?

**Comment by Letsplaybar** [comment]
@JayWood  oh sorry has the wrong version have jet th rigth updatet.
have jet this im log:
`[14:39:44] [Server thread/INFO]: Letsplaybar[/87.168.177.38:35486] logged in with entity id 25 at ([lobbyServer]0.3751570228058439, 40.0, 0.40666330810947576)
[14:40:04] [Server thread/INFO]: Letsplaybar issued server command: /woo check
[14:44:51] [Thread-10/INFO]: UUID of player TheRiveHD is bbae096a-3a45-439e-beb7-5a89a2318cad
[14:44:51] [Server thread/INFO]: TheRiveHD[/93.200.248.138:58613] logged in with entity id 27 at ([lobbyServer]0.3751570228058439, 40.0, 0.40666330810947576)
[14:45:08] [Server thread/INFO]: TheRiveHD lost connection: Disconnected
[14:52:04] [Server thread/INFO]: Letsplaybar issued server command: /woo check
[14:52:04] [Server thread/INFO]: [WooMinecraft] []
[14:52:04] [Server thread/WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]
[14:52:04] [Server thread/WARN]: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
[14:52:04] [Server thread/WARN]: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[14:52:04] [Server thread/WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:195)
[14:52:04] [Server thread/WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:319)
[14:52:04] [Server thread/WARN]: 	at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:206)
[14:52:04] [Server thread/WARN]: 	at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:31)
[14:52:04] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:52:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:52:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[14:52:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[14:52:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[14:52:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:52:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:52:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[14:52:04] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:52:04] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:52:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[14:52:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[14:52:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[14:52:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[14:52:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[14:52:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)`
@eric2788 jes

**Comment by JayWood** [comment]
@Letsplaybar this is unusual, it's not typical for the `wp_send_json_error()` or even `wp_send_json_success()` to send just an array `[14:52:04] [Server thread/INFO]: [WooMinecraft] []`

This is where the error is occurring - https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/java/com/plugish/woominecraft/WooMinecraft.java#L206 

I'll have to push more debug code for this portion today.

@eric2788 I realize your frustration, and sympathize. Please understand that this plugin is getting built on my free time, and I'm not being paid so you can get paid ( it is a donation plugin after all ) so please bear with me during these times and know that I really appreciate the feedback and bug reports.

**Comment by Jogib** [comment]
@JayWood 
I've been digging around a little with this issue...

And I've actually managed to install both the java and WP plugin, and get them to connect without errors and successfully execute the command given to the given product!!

The way i did it:
1. Installed java plugin
2. Started and stopped the server to generate config files
3. Manually added a random key - Since you disabled the "/woo register" command
4. Added my domain name
5. Installed the WP plugin
6. Added the random key i manually made in the java plugin
7. Started the MC server
7. Did a "/woo check" ingame and got the following message: [WooMinecraft]  No purchases available - please try again soon.
8. Created a product in WP and bought it
9. Logged in to my MC server and received my item right after executing "/woo check"

**Comment by JayWood** [comment]
@Jogib The proper way of handling configs, you're spot on there. Had you re-ran `/woo check` afterwards to see if it re-sent the items to you?

**Comment by JayWood** [comment]
@Jogib if you're still getting a similar issue as above can you verify what version of the WordPress plugin you're using?

@Letsplaybar Are you on the latest WordPress version as well?

**Comment by JayWood** [comment]
Instead of waiting for a reply, tested this for myself. The `[]` in the message signifies the empty array it's sending to WordPress, because no users were processed. So I tested this with users not online, but still pending donations, attached is the screenshot.

![dd8d6fb737ba22c06759b799094d6cdc](https://cloud.githubusercontent.com/assets/2303074/18297659/53279b94-7480-11e6-85be-b84e5742b14e.png)

I cannot replicate the exception, WordPress is sending back the proper response. So at this point I'll need more information :cry:

**Comment by eric2788** [comment]
> 3. Manually added a random key - Since you disabled the "/woo register" command

i still cannot understand how to get a key......

**Comment by Letsplaybar** [comment]
@JayWood  yes wordpress is on the last version I upgrade all on my Wordpress side dayly
that have i Make:
1. update all resouces
2. delet the old product
3. buy the new product
4. command /woo check in Minecraft on the server
5.show in the last.log and find evry when i make /woo check or the scheduler run the error.

i hope this informations can help you

**Comment by Letsplaybar** [comment]
and this comes when i this make with me Minecraft acount:
`[16:22:51] [Server thread/INFO]: Letsplaybar issued server command: /woo check
[16:22:51] [Server thread/INFO]: [WooMinecraft] [340]
[16:22:51] [Server thread/WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]
[16:22:51] [Server thread/WARN]: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
[16:22:51] [Server thread/WARN]: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[16:22:51] [Server thread/WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:195)
[16:22:51] [Server thread/WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:319)
[16:22:51] [Server thread/WARN]: 	at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:206)
[16:22:51] [Server thread/WARN]: 	at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:31)
[16:22:51] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:22:51] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:22:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[16:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[16:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:22:51] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:22:51] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:22:51] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:22:52] [Server thread/INFO]: Given 1 levels to Letsplaybar`
and it woudn't remove that i can evry thimes again and become everythimes the coins.
i think it wouldn't remove from wordpress

**Comment by Jogib** [comment]
@JayWood After the step by step I wrote yesterday I'm not receiving any errors.
No errors anywhere.
Theres only the little things left, I have written about in #110 😄 

@Letsplaybar I must admit, that I'm lost about what your problem actually is?
What is it, exactly that doesn't work?

**Comment by JayWood** [comment]
@Letsplaybar This tells me it's sending order #340 back to your server here - `[16:22:51] [Server thread/INFO]: [WooMinecraft] [340]`

The reason your order is re-running is for some reason you're getting an error when it sends that order, so WordPress doesn't know to process the order, and remove it from the pending list.

The only thing I can think of at this point is that for some reason your server isn't allowing $_POST data to be sent from your Minecraft server. Not sure if it's a firewall issue or not. What I can do though is add an extra debug here so we can see what you're getting back.

**Comment by Letsplaybar** [comment]
i have not firewall aktive momentanly and right to write and read shoud the server have.

**Comment by Letsplaybar** [comment]
and newst kickt the server me by run the methode

**Comment by falmon** [comment]
problem  with /woo check

`[04:16:34] [Server thread/WARN]: [WooMinecraft] Logging an improper server response
[04:16:34] [Server thread/ERROR]: [WooMinecraft] /<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=http://www.twsmc.net"></head><body></body></html>/
[04:16:34] [Server thread/WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]
[04:16:34] [Server thread/WARN]: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
[04:16:34] [Server thread/WARN]: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[04:16:34] [Server thread/WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:195)
[04:16:34] [Server thread/WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:319)
[04:16:34] [Server thread/WARN]: 	at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:142)
[04:16:34] [Server thread/WARN]: 	at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:31)
[04:16:34] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[04:16:34] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[04:16:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[04:16:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[04:16:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[04:16:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[04:16:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[04:16:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[04:16:34] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
`

config.yml:
`
lang: "en"


update_interval: 1500

url: "http://twsmc.net"  #  or http://www.twsmc.net = same problem


key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"


debug: true`


i'm useing https://github.com/WooMinecraft/WooMinecraft/releases   18#
wordpress 4.6 - 1.0.8

**Comment by JayWood** [comment]
@Letsplaybar I can't make out your last message. I'll work this weekend on adding a debug to that last http request, should give us more information.

**Comment by JayWood** [comment]
Closing this, tracking new debugging in the above linked task.
